services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 256m
    cpus: '0.5'
    command: sh -c "npx prisma migrate deploy && node dist/src/main"
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    networks:
      - mio-network

  db:
    image: postgres:15-alpine
    mem_limit: 512m
    cpus: '1.0'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mio-network

networks:
  mio-network:
    driver: bridge

volumes:
  postgres_data:
